max-width 2048
max-height 2048
power-of-two true

output "Samples/AcornJump/AcornJump/Resources/acornjump{0-}.png"
description "Samples/AcornJump/AcornJump/Resources/acornjump.json"
  template ".agents/skills/spright-spritesheet-skill/templates/acorn.inja"

id "{{ source.filenameStem }}"
glob "Samples/AcornJump/assets/sprites/*.png"
